### PR TITLE
Implemented string contains

### PR DESCRIPTION
**Pull request by Gimly**
Added special case for the Contains case of the filter when there is only one argument. It checks if the parameter of the contains is a string and, in that case, uses a regex to return.

### CODE REVIEW

**Comment by colethecoder** [comment]
I haven't merged this yet because counting the arguments to determine how to deal with it seems like it could be error-prone. I think it might be better for `MethodCallExpressionToString` to switch on `methodCallExpression.Method.DeclaringType` and then call specific functions for Enumerable / String. I haven't tested it but I think if you had a custom type with a Contains method you could get some weird behaviour with the current implementation.

**Comment by Gimly** [comment]
Yes, you're totally right, I'll update that.

**Comment by Gimly** [comment]
@colethecoder Is there anything else you need me to do before merging this? I need this in my current project and it would be awesome if I could just grab the version from NuGet.

**Comment by colethecoder** [comment]
I'll merge tonight, at a quick glance it looks good. If everything goes OK it'll be on Nuget this evening.

**Comment by colethecoder** [comment]
Released to Nuget as:

https://www.nuget.org/packages/Chronological/1.0.105

Thanks for implementing all of that!

**Pull request merged**
